### PR TITLE
detect mingw byte order

### LINKED ISSUE #2073: Compilation failure on MinGW-w64 (x86_64)
`building 'borg.hashindex' extension`
`C:\msys64\mingw64\bin/x86_64-w64-mingw32-gcc.exe -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -D_FORTIFY_SOURCE=2 -IC:/msys64/mingw64/include/python3.5m -c borg/hashindex.c -o build/temp.mingw-3.5/borg/hashindex.o`
`In file included from borg/hashindex.c:433:0:`
`borg/_hashindex.c:24:2: error: #error Unknown byte order`
` #error Unknown byte order`
 ` ^~~~~`
`borg/_hashindex.c: In function 'hashindex_index':`
`borg/_hashindex.c:108:12: warning: implicit declaration of function '_le32toh' [-Wimplicit-function-declaration]`
`     return _le32toh(*((uint32_t *)key)) % index->num_buckets;`
`            ^~~~~~~~`
`borg/_hashindex.c: In function 'hashindex_lookup':`
`borg/_hashindex.c:76:15: warning: implicit declaration of function '_htole32' [-Wimplicit-function-declaration]`
` #define EMPTY _htole32(0xffffffff)`
`               ^`
`borg/_hashindex.c:84:100: note: in expansion of macro 'EMPTY'`
` #define BUCKET_IS_EMPTY(index, idx) (*((uint32_t *)(BUCKET_ADDR(index, idx) + index->key_size)) == EMPTY)`
`                                                                                                    ^~~~~`
`borg/_hashindex.c:118:12: note: in expansion of macro 'BUCKET_IS_EMPTY'`
 `        if(BUCKET_IS_EMPTY(index, idx))`
`            ^~~~~~~~~~~~~~~`
`error: command 'C:\\msys64\\mingw64\\bin/x86_64-w64-mingw32-gcc.exe' failed with exit status 1`
`==> ERROR: A failure occurred in build().`
 `   Aborting...`

### PR DESCRIPTION
**Pull request by enkore**
Fixes #2073

@oroppas feel free to check if this actually fixes it (although I have little doubt)

657ecfd aimed at master (crc, hashindex dedup).

### CODE REVIEW

File: borg/_hashindex.c [hunk 1]
```diff
@@ -13,10 +13,12 @@
 #endif
 
 #if (defined(BYTE_ORDER)&&(BYTE_ORDER == BIG_ENDIAN)) ||  \
+    (defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)) || \
```
Comment (ThomasWaldmann) [inline borg/_hashindex.c]: keep the tight style (no blanks around &&) and do the style change globally later?
